//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blog.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artigo.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesse no desenvolvimento de sistemas em .NET/Java. Sou autodidata e participo de fóruns da área de desenvolvimento, busco conhecer melhores práticas e as novidades do mercado nesta área..
        /// </summary>
        internal static string Author_desc {
            get {
                return ResourceManager.GetString("Author_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha.
        /// </summary>
        internal static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaisquer dúvias ou críticas entre em contato comigo será um prazer poder discutir ofertas, trabalhos ou qualquer outra coisa. .
        /// </summary>
        internal static string Contact_main {
            get {
                return ResourceManager.GetString("Contact_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível deletar!.
        /// </summary>
        internal static string Delete_error {
            get {
                return ResourceManager.GetString("Delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail foi digitado é inválido..
        /// </summary>
        internal static string Email_inv {
            get {
                return ResourceManager.GetString("Email_inv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo E-mail é requirido!.
        /// </summary>
        internal static string Email_req {
            get {
                return ResourceManager.GetString("Email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao enviar arquivo!.
        /// </summary>
        internal static string File_error {
            get {
                return ResourceManager.GetString("File_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manter Logado?.
        /// </summary>
        internal static string Logado {
            get {
                return ResourceManager.GetString("Logado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campo senha, no máximo 12 caracteres!.
        /// </summary>
        internal static string Password_max {
            get {
                return ResourceManager.GetString("Password_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campo senha, no minimo 8 caracteres!.
        /// </summary>
        internal static string Password_min {
            get {
                return ResourceManager.GetString("Password_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo senha é requirido!.
        /// </summary>
        internal static string Password_req {
            get {
                return ResourceManager.GetString("Password_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguns projetos que desenvolvi para estudo de algumas frameworks de Java e alguns projetos feitos para terceitos.  Dê uma olhada!.
        /// </summary>
        internal static string Project_desc {
            get {
                return ResourceManager.GetString("Project_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projetos.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguns projetos que desenvolvi para estudo de algumas frameworks de Java e alguns projetos feitos para terceitos. Dê uma olhada!.
        /// </summary>
        internal static string Projects_main {
            get {
                return ResourceManager.GetString("Projects_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saber Mais.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse e-mail já existe em nossa base de dados. .
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha atual está incorreta ou a nova senha é inválida..
        /// </summary>
        internal static string TrocaSenha {
            get {
                return ResourceManager.GetString("TrocaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        internal static string Tutorials {
            get {
                return ResourceManager.GetString("Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muito em breve vou tentar compartilhar alguns Tutoriais  com vocês e espero que seja de algum proveito. .
        /// </summary>
        internal static string Tutorials_desc {
            get {
                return ResourceManager.GetString("Tutorials_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muito em breve vou tentar compartilhar alguns Tutoriais com vocês e espero que seja de algum proveito..
        /// </summary>
        internal static string Tutorials_main {
            get {
                return ResourceManager.GetString("Tutorials_main", resourceCulture);
            }
        }
    }
}
